image: ruby:2.7

pipelines:
  default:
    - step:
        caches:
          - bundler
        script:
          - git config --global user.email "navy.applee@gmail.com"
          - git config --global user.name "deeplify"
          - bundle install
          - JEKYLL_ENV=production bundle exec jekyll build
          - git add . && git commit -m "updates"
          - git checkout -b master
          - git filter-branch --subdirectory-filter _site/ -- --all
          - rm -rf bitbucket-pipelines.yml
          - git add . && git commit -m "updates"
          - git push -f origin master
          
definitions:
  caches:
    bundler: vendor/bundle