name: Jekyll Build and Deploy

# main 브랜치에 변경 사항이 있을 때 실행
on:
  push:
    branches:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.5'
    - name: Install Bundler
      run: gem install bundler
    - name: Install dependencies
      run: bundle install
    - name: Build Jekyll site
      run: JEKYLL_ENV=production bundle exec jekyll build
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        publish_branch: master
        # Optional: Add cname if you're using a custom domain
        cname: www.deeplify.dev